Connect to cs157a;
ALTER TABLE HW3.Student DROP CONSTRAINT NoDup;
ALTER TABLE HW3.Class DROP CONSTRAINT primaryKeyClassID;
ALTER TABLE HW3.ClassReq DROP CONSTRAINT classIDForeignKey;
ALTER TABLE HW3.Schedule DROP CONSTRAINT foreignKeys;
DROP TRIGGER CannotTake;

DROP TABLE HW3.Student;
DROP TABLE HW3.Class;
DROP TABLE HW3.ClassReq;
DROP TABLE HW3.Schedule;
Terminate;
